name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - uses: Harmon758/postgresql-action@v1.0.0
    - name: Setup PostgreSQL
      with:
        postgresql db: ${{ secrets.DB_NAME }}
        postgresql user: ${{ secrets.DB_USER }}
        postgresql password: ${{ secrets.DB_PASSWORD }}
        postgresql host: "localhost"
        postgresql port: 5432
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} > .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_HOST="localhost" >> .env
        echo DB_PORT="5432" >> .env
        
    - name: Run Tests
      run: |
        python manage.py test
